## **Dataset**

https://raw.githubusercontent.com/damahindra/TechSeriesMLHOP/main/Challenge!/DiamondsDataset.csv

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/damahindra/TechSeriesMLHOP/main/Challenge!/DiamondsDataset.csv', index_col='Unnamed: 0')
data

       carat        cut color clarity  depth  table  price     x     y     z
1       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

## Handle Outliers

### Remove them

In [4]:
# Create a Pandas DataFrame with some sample data
data1 = data.copy()

for col in data1.select_dtypes('number') :
    # Calculate the first and third quartiles (Q1 and Q3)
    Q1 = data1[col].quantile(0.25)
    Q3 = data1[col].quantile(0.75)

    # Calculate the IQR (Interquartile Range)
    IQR = Q3 - Q1

    # Define the lower and upper bounds for outlier removal
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Use loc to filter out outliers
    data1 = data1.loc[(data1[col] >= lower_bound) & (data1[col] <= upper_bound)]

# Print the filtered data
data1

       carat        cut color clarity  depth  table  price     x     y     z
1       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
4       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[46532 rows x 10 columns]

### Replace Them

In [5]:
# Create a Pandas DataFrame with some sample data
data2 = data.copy()

for col in data2.select_dtypes('number') :
    # Calculate the first and third quartiles (Q1 and Q3)
    Q1 = data2[col].quantile(0.25)
    Q3 = data2[col].quantile(0.75)

    # Calculate the IQR (Interquartile Range)
    IQR = Q3 - Q1

    # Define the lower and upper bounds for outlier removal
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Use loc to filter out outliers
    data2[col] = data2[col].apply(lambda x : Q3 if x > upper_bound else Q1 if x < lower_bound else x)

# Print the filtered data
data2

       carat        cut color clarity  depth  table   price     x     y     z
1       0.23      Ideal     E     SI2   61.5   55.0   326.0  3.95  3.98  2.43
2       0.21    Premium     E     SI1   59.8   61.0   326.0  3.89  3.84  2.31
3       0.23       Good     E     VS1   61.0   59.0   327.0  4.05  4.07  2.31
4       0.29    Premium     I     VS2   62.4   58.0   334.0  4.20  4.23  2.63
5       0.31       Good     J     SI2   63.3   58.0   335.0  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...     ...   ...   ...   ...
53936   0.72      Ideal     D     SI1   60.8   57.0  2757.0  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0  2757.0  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0  2757.0  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0  2757.0  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0  2757.0  5.83  5.87  3.64

[53940 rows x 10 columns]

## Comparison

In [9]:
print(f'Initial Data Skew\n\n{data.skew()}\n')
print(f'Remove Outliers Data Skew\n\n{data1.skew()}\n')
print(f'Replace Outliers Data Skew\n\n{data2.skew()}\n')

'''
To do :
 - Remove Outliers : depth, x, y, z
 - Replace Outliers : carat, table
'''

Initial Data Skew

carat    1.116646
depth   -0.082294
table    0.796896
price    1.618395
x        0.378676
y        2.434167
z        1.522423
dtype: float64

Remove Outliers Data Skew

carat    0.685771
depth   -0.197832
table    0.397247
price    1.143553
x        0.255111
y        0.248553
z        0.250499
dtype: float64

Replace Outliers Data Skew

carat    0.645510
depth   -0.231262
table    0.345430
price    1.036086
x        0.386032
y        0.382294
z        0.378569
dtype: float64

'\nTo do :\n - Remove Outliers\n'

In [10]:
# Create a Pandas DataFrame with some sample data
clean_outliers = data.copy()

for col in ['depth', 'x', 'y', 'z'] :
    # Calculate the first and third quartiles (Q1 and Q3)
    Q1 = clean_outliers[col].quantile(0.25)
    Q3 = clean_outliers[col].quantile(0.75)

    # Calculate the IQR (Interquartile Range)
    IQR = Q3 - Q1

    # Define the lower and upper bounds for outlier removal
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Use loc to filter out outliers
    clean_outliers = clean_outliers.loc[(clean_outliers[col] >= lower_bound) & (clean_outliers[col] <= upper_bound)]

for col in ['carat', 'table'] :
    # Calculate the first and third quartiles (Q1 and Q3)
    Q1 = clean_outliers[col].quantile(0.25)
    Q3 = clean_outliers[col].quantile(0.75)

    # Calculate the IQR (Interquartile Range)
    IQR = Q3 - Q1

    # Define the lower and upper bounds for outlier removal
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Use loc to filter out outliers
    clean_outliers[col] = clean_outliers[col].apply(lambda x : Q3 if x > upper_bound else Q1 if x < lower_bound else x)

# Print the filtered data
clean_outliers

       carat        cut color clarity  depth  table  price     x     y     z
1       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
4       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[51350 rows x 10 columns]

## Handle Skew

Using scipy's boxcox transformation to handle skewness

In [21]:
import scipy.stats as stats

handle_skew = clean_outliers.copy()

for col in handle_skew.select_dtypes('number') : 
    handle_skew[col], lambda_value = stats.boxcox(handle_skew[col])

handle_skew

,carat,cut,color,clarity,depth,table,price,x,y,z
1,-1.473087,Ideal,E,SI2,3.166111e+09,0.34312,4.641634,1.076655,1.083841,0.765732
2,-1.564494,Premium,E,SI1,2.695936e+09,0.34312,4.641634,1.067427,1.062116,0.728028
4,-1.240294,Premium,I,VS2,3.441204e+09,0.34312,4.656946,1.113133,1.120151,0.823326
5,-1.173348,Good,J,SI2,3.735739e+09,0.34312,4.658832,1.132287,1.136555,0.855134
6,-1.430332,Very Good,J,VVS2,3.569646e+09,0.34312,4.660712,1.075131,1.080802,0.780713
...,...,...,...,...,...,...,...,...,...,...
53936,-0.328674,Ideal,D,SI1,2.964932e+09,0.34312,5.883381,1.287396,1.292201,1.018906
53937,-0.328674,Good,D,SI1,3.668553e+09,0.34312,5.883381,1.281898,1.291286,1.038959
53938,-0.356876,Very Good,D,SI1,3.569646e+09,0.34312,5.883381,1.279119,1.284821,1.029947
53939,-0.150859,Premium,H,SI2,3.021303e+09,0.34312,5.883381,1.322143,1.323758,1.061627
53940,-0.287813,Ideal,D,SI2,3.378429e+09,0.34312,5.883381,1.294606,1.302124,1.044286

In [22]:
handle_skew.skew()

carat    0.000715
depth   -0.002590
table    0.000000
price    0.030992
x        0.026969
y        0.026619
z        0.024565
dtype: float64

In [23]:
lambda_value # use for transforming back to original value

-0.34206266778739264

## Splitting into Train and Test Data

In [24]:
from sklearn.model_selection import train_test_split

X = handle_skew.drop('price', axis=1)
y = handle_skew['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

## Encoding and Scaling

Using sklearn's OneHotEncoder and StandardScaler

In [46]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

cat_cols = list(X.select_dtypes('object'))
num_cols = list(X.select_dtypes('number'))

encoder = OneHotEncoder()

scaler = StandardScaler()

# train data
X_train_encoded = pd.DataFrame(data=encoder.fit_transform(X_train[cat_cols]).toarray(), index=X_train.index, columns=encoder.get_feature_names_out(cat_cols))
X_train_scaled = pd.DataFrame(data=scaler.fit_transform(X_train[num_cols]), index=X_train.index, columns=num_cols)

full_train = pd.concat([X_train_encoded, X_train_scaled, y_train], axis=1).reset_index(drop=True)

# test data
X_test_encoded = pd.DataFrame(data=encoder.transform(X_test[cat_cols]).toarray(), index=X_test.index, columns=encoder.get_feature_names_out(cat_cols))
X_test_scaled = pd.DataFrame(data=scaler.fit_transform(X_test[num_cols]), index=X_test.index, columns=num_cols)

full_test = pd.concat([X_test_encoded, X_test_scaled, y_test], axis=1).reset_index(drop=True)

## Export

In [47]:
full_train.to_csv('Preprocessed/full_train.csv')
full_test.to_csv('Preprocessed/full_test.csv')